{% set name = "forbiddenfruit" %}
{% set version = "0.1.4" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/forbiddenfruit-{{ version }}.tar.gz
  sha256: e3f7e66561a29ae129aac139a85d610dbf3dd896128187ed5454b6421f624253

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 1

requirements:
  host:
    - python {{ python_min }}
    - pip
  run:
    - python >={{ python_min }}

test:
  imports:
    - forbiddenfruit
  commands:
    - pip check
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://github.com/clarete/forbiddenfruit
  summary: Patch python built-in objects
  license: LGPL-3.0-only & MIT
  license_file:
    - COPYING
    - COPYING.mit

extra:
  recipe-maintainers:
    - aymondebroglie
